services:
  db:
    image: postgres:16-alpine
    container_name: axumblogdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: axum_lite
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d axum_lite"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
    container_name: axum_blog_migrate
    environment:
      DATABASE_URL: postgres://user:password@db:5432/axum_lite
      JWT_SECRET: dev-secret
    depends_on:
      db:
        condition: service_healthy
    command: ["migrate"]

  app:
    build:
      context: .
    container_name: axum_blog_api
    environment:
      DATABASE_URL: postgres://user:password@db:5432/axum_lite
      SERVER_ADDRESS: 0.0.0.0:7870
      JWT_SECRET: dev-secret
    ports:
      - "7870:7870"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  pg_data:
